services:
  - type: web
    name: booklist-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn booklist_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: booklist_project.settings
      - key: PYTHON_VERSION
        value: 3.10
