services:
  - type: web
    name: booklist-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn booklist_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: booklist_project.settings
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: DATABASE_URL
        fromDatabase:
          name: booklist-db
          property: connectionString

databases:
  - name: booklist-db
    databaseName: booklist
    user: booklist_user
